#!/usr/bin/env bash

set -e

echo "Checking for updates..."
git pull

echo "Creating symbolic links to dot files... "

for name  in dot/* ; do
  target="$HOME/.`basename $name`"
  if [ -e "$target" ]; then
    if [ ! -L "$target" ]; then
      echo "WARNING: $target exists but is not a symlink."
      echo Backuping file $target to "$target"_old
      mv $target "${target}_old"
    else
      echo "${target} is already linked"
    fi
  else
    echo "Linking  $target"
    ln -s "$PWD/$name" "$target"
  fi
done

echo "Linking neovim files... "
mkdir -p "${HOME}/.config/nvim"
if [ ! -L "${HOME}/.config/nvim/init.vim" ]; then
  ln -s ~/.vimrc ~/.config/nvim/init.vim
else
  echo "Ignored. It's already linked"
fi

vim -u ~/.vimrc +"PlugInstall" +"PlugClean" +qa

echo "Installation completed"
exit 0
